# Generated by Django 5.2.6 on 2025-09-22 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='option',
            new_name='polls_optio_poll_id_70539b_idx',
            old_name='poll_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='polls_vote_poll_id_cee50f_idx',
            old_name='vote_poll_idx',
        ),
        migrations.RenameIndex(
            model_name='vote',
            new_name='polls_vote_option__9fc1fb_idx',
            old_name='vote_option_idx',
        ),
    ]
